import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="h-screen flex flex-col items-center justify-center relative">
        <div className="absolute top-0 left-0 w-full h-full bg-[#e8f0f7]"></div>
        <div className="absolute top-0 left-0 w-full h-full bg-[#4d5bf9]"></div>
        <div className="relative z-10 grid grid-cols-2 gap-6 rounded-xl p-4 pr-4 bg-white shadow-md sm:w-10/12 md:w-10/12 w-7/12 h-4/5">
          <div className="flex items-center justify-center bg-gray-200 rounded-lg p-4 relative z-20 px-6">01</div>
          <div className="flex items-center justify-center bg-gray-200 rounded-lg p-4 relative z-20 w-2/3">09</div>
        </div>
      </main>
    </>
  )
}
